/// <reference lib="dom" />
//import { installDelphineRuntime } from "./src/drt"; // <-- TS, pas .js
import { TForm, TColor, TApplication } from './vcl/StdCtrls';

class Zaza extends TForm {
        // Form components - This list is auto generated by Delphine
        // ---------------
        //button1 : TButton = new TButton("button1", this, this);
        //button2 : TButton = new TButton("button2", this, this);
        //button3 : TButton = new TButton("button3", this, this);
        // ---------------

        constructor(name: string) {
                super(name);
        }
        //import { installDelphineRuntime } from "./drt";

        /*
const runtime = {
  handleClick({ element }: { element: Element }) {
    console.log("clicked!", element);
    //(element as HTMLElement).style.backgroundColor = "red";
  },
};
*/

        button1_onclick() {
                const btn = this.componentRegistry.get('button1');
                if (!btn) {
                        console.warn('button1 not found in registry');
                        return;
                }
                btn.color = TColor.rgb(0, 255, 0);
                this.componentRegistry.get('button1')!.color = TColor.rgb(255, 0, 0);
                console.log('Button1 clicked!!!!');
        }

        zaza_onclick() {
                this.componentRegistry.get('button1')!.color = TColor.rgb(0, 255, 0);
                console.log('zaza clicked!!!!');
        }

        //installDelphineRuntime(runtime);
} // class zaza

class MyApplication extends TApplication {
        private runWhenDomReady(fn: () => void) {
                if (document.readyState === 'loading') {
                        window.addEventListener('DOMContentLoaded', fn, { once: true });
                } else {
                        fn();
                }
        }

        zaza: Zaza;

        forceFocus() {
                try {
                        // rendre le body focusable
                        if (document.body && document.body.tabIndex < 0) document.body.tabIndex = -1;
                        window.focus();
                        document.body?.focus();
                        console.log('forceFocus done', { hasFocus: document.hasFocus() });
                } catch (e) {
                        console.log('forceFocus failed', e);
                }
        }

        run() {
                window.addEventListener('load', () => {
                        this.forceFocus();
                        // re-tentative courte (VSCode peut “re-hooker” la webview juste après)
                        setTimeout(this.forceFocus, 0);
                        setTimeout(this.forceFocus, 50);
                        setTimeout(this.forceFocus, 200);
                });
                //this.zaza.componentRegistry.buildComponentTree(this.zaza);
                //this.zaza.addEventListener('click');

                // au lancement
                this.runWhenDomReady(() => {
                        this.zaza.componentRegistry.buildComponentTree(this.zaza);
                });
                this.zaza.show();
        }
        constructor() {
                super();
                this.zaza = new Zaza('zaza');
        }
} // class MyApplication

const myApplication: MyApplication = new MyApplication();
myApplication.run();
