/// <reference lib="dom" />
//import { installDelphineRuntime } from "./src/drt"; // <-- TS, pas .js
console.log('🔥 I AM ZAZAVUE – ENTRY EXECUTED')

console.log('I AM ZAZAVUE')

import { TForm, TColor, TApplication, TComponent, TButton, PluginRegistry, TPanel } from '@vcl'
//import { TPluginHost } from '@drt/UIPlugin'
import { createHelloVuePlugin } from './createHelloVuePlugin'

console.log('I AM ZAZAVUE')

// oxlint-disable-next-line no-debugger
debugger

//import type { DelphineServices } from '@drt/UIPlugin' // adaptez le chemin exact chez vous
//import { ComponentRegistry } from '@drt/ComponentRegistry';
//import { TPluginHost } from '@drt/UIPlugin';

//export function registerPluginTypes(reg: ComponentTypeRegistry): void {
/*
        // Example: any type name can be provided by a plugin.
        reg.register.registerType('chartjs-pie', (name: string, form: TForm, parent: TComponent) => {
                return new PluginHost(name, form, parent);
        });

        reg.registerType('vue-hello', (name: string, form: TForm, parent: TComponent) => {
                return new PluginHost(name, form, parent);
        });
        */
//}

class ZazaVue extends TForm {
  // Form components - This list is auto generated by Delphine
  // ---------------
  //button1 : TButton = new TButton("button1", this, this);
  //button2 : TButton = new TButton("button2", this, this);
  //button3 : TButton = new TButton("button3", this, this);
  // ---------------

  constructor(name: string) {
    super(name)
  }
  //import { installDelphineRuntime } from "./drt";

  /*
const runtime = {
  handleClick({ element }: { element: Element }) {
    console.log("clicked!", element);
    //(element as HTMLElement).style.backgroundColor = "red";
  },
};
*/

  protected onMyCreate(_ev: Event | null, _sender: TComponent) {
    //const btn = this.componentRegistry.get('button1')
    //if (btn) btn.color = TColor.rgb(0, 0, 255)
  }

  protected onMyShown(_ev: Event | null, _sender: TComponent) {
    //const btn = this.componentRegistry.get('buttonx')
    //if (btn) btn.color = TColor.rgb(0, 255, 255)
  }

  button1_onclick(_ev: Event | null, _sender: TComponent) {
    const btn = this.componentRegistry.get<TButton>('button1')
    if (!btn) {
      console.warn('button1 not found in registry')
      return
    }
    //btn.color = TColor.rgb(0, 0, 255);
    btn!.color = TColor.rgb(0, 0, 255)
    btn!.caption = 'MIMI'
    btn!.enabled = false
    console.log('Button1 clicked!!!!')
  }

  subButton1_onclick(_ev: Event | null, _sender: TComponent) {
    const panel = this.componentRegistry.get<TPanel>('myPanel')
    if (!panel) {
      console.warn('myPanel not found in registry')
      return
    }
    //btn.color = TColor.rgb(0, 0, 255);
    panel!.backgroundColor = TColor.rgb(54, 127, 173)
  }

  zaza_onclick(_ev: Event | null, _sender: TComponent) {
    const btn = this.componentRegistry.get<TButton>('buttonx')
    btn!.color = TColor.rgb(0, 255, 0)
    console.log('zazaVue clicked!!!!')
    //btn!.enabled = false;
  }

  //installDelphineRuntime(runtime);
} // class zaza

class MyApplication extends TApplication {
  zazaVue: ZazaVue

  constructor() {
    super()
    this.zazaVue = new ZazaVue('zazaVue')
    this.mainForm = this.zazaVue
    PluginRegistry.pluginRegistry.register('hello-vue', { factory: createHelloVuePlugin })
  }

  run() {
    //this.zaza.componentRegistry.buildComponentTree(this.zaza);
    //this.zaza.addEventListener('click');

    // au lancement
    this.runWhenDomReady(() => {
      this.zazaVue.show()
    })
  }
} // class MyApplication

const myApplication: MyApplication = new MyApplication()
myApplication.run()
