/// <reference lib="dom" />
console.log('I AM ZAZA');
//import { installDelphineRuntime } from "./src/drt"; // <-- TS, pas .js
import { TForm, TColor, TApplication, TComponent, TButton } from '@vcl';
//import { ComponentTypeRegistry } from '@vcl/StdCtrls';
//import { ComponentRegistry } from '@drt/ComponentRegistry';
//import { TPluginHost } from '@drt/UIPlugin';
/*
export function registerPluginTypes(reg: ComponentTypeRegistry): void {
        / *
        // Example: any type name can be provided by a plugin.
        reg.register.registerType('chartjs-pie', (name: string, form: TForm, parent: TComponent) => {
                return new PluginHost(name, form, parent);
        });

        reg.registerType('vue-hello', (name: string, form: TForm, parent: TComponent) => {
                return new PluginHost(name, form, parent);
        });
        * /
}
*/
console.log('I AM ZAZA');

class Zaza extends TForm {
        // Form components - This list is auto generated by Delphine
        // ---------------
        //button1 : TButton = new TButton("button1", this, this);
        //button2 : TButton = new TButton("button2", this, this);
        //button3 : TButton = new TButton("button3", this, this);
        // ---------------

        constructor(name: string) {
                super(name);
        }
        //import { installDelphineRuntime } from "./drt";

        /*
const runtime = {   
  handleClick({ element }: { element: Element }) {
    console.log("clicked!", element);
    //(element as HTMLElement).style.backgroundColor = "red";
  },
}; 
*/

        protected onMyCreate(_ev: Event | null, _sender: TComponent) {
                const btn = this.componentRegistry.get('button2');
                if (btn) btn.color = TColor.rgb(0, 0, 255);
        }

        protected onMyShown(_ev: Event | null, _sender: TComponent) {
                const btn = this.componentRegistry.get('button3');
                if (btn) btn.color = TColor.rgb(0, 255, 255);
        }

        button1_onclick(_ev: Event | null, _sender: TComponent) {
                const btn = this.componentRegistry.get<TButton>('button1');
                if (!btn) {
                        console.warn('button1 not found in registry');
                        return;
                }
                //btn.color = TColor.rgb(0, 0, 255);
                btn!.color = TColor.rgb(255, 0, 0);
                btn!.setCaption('MIMI');
                console.log('Button1 clicked!!!!');
        }

        zaza_onclick(_ev: Event | null, _sender: TComponent) {
                const btn = this.componentRegistry.get<TButton>('buttonx');
                btn!.color = TColor.rgb(0, 255, 0);
                console.log('zaza clicked!!!!');
                //btn!.enabled = false;
        }

        //installDelphineRuntime(runtime);
} // class zaza

class MyApplication extends TApplication {
        zaza: Zaza;

        constructor() {
                super();
                this.zaza = new Zaza('zaza');
                this.mainForm = this.zaza;
        }

        run() {
                //this.zaza.componentRegistry.buildComponentTree(this.zaza);
                //this.zaza.addEventListener('click');

                // au lancement
                this.runWhenDomReady(() => {
                        this.zaza.show();
                });
        }
} // class MyApplication

const myApplication: MyApplication = new MyApplication();
myApplication.run();
