'use strict';
Object.defineProperty(exports, '__esModule', { value: true });

/// <reference lib="dom" />
//import { installDelphineRuntime } from "./src/drt"; // <-- TS, pas .js
//const _vcl_1 = require('@vcl');
const { TColor } = require('../../../delphine 2/vcl/StdCtrls');
class Zaza extends TForm {
        // Form components - This list is auto generated by Delphine
        // ---------------
        //button1 : TButton = new TButton("button1", this, this);
        //button2 : TButton = new TButton("button2", this, this);
        //button3 : TButton = new TButton("button3", this, this);
        // ---------------
        constructor(name) {
                super(name);
        }
        //import { installDelphineRuntime } from "./drt";
        /*
const runtime = {
handleClick({ element }: { element: Element }) {
console.log("clicked!", element);
//(element as HTMLElement).style.backgroundColor = "red";
},
};
*/

        button1_onclick() {
                const btn = this.componentRegistry.get('button1');
                if (!btn) {
                        console.warn('button1 not found in registry');
                        return;
                }
                //btn.color = TColor.rgb(0, 0, 255);
                this.componentRegistry.get('button1').color = _vcl_1.TColor.rgb(255, 0, 0);
                console.log('Button1 clicked!!!!');
        }
        zaza_onclick() {
                this.componentRegistry.get('button1').color = _vcl_1.TColor.rgb(0, 255, 0);
                console.log('zaza clicked!!!!');
        }
} // class zaza
class MyApplication extends TApplication {
        runWhenDomReady(fn) {
                if (document.readyState === 'loading') {
                        window.addEventListener('DOMContentLoaded', fn, { once: true });
                } else {
                        fn();
                }
        }
        zaza;
        run() {
                //this.zaza.componentRegistry.buildComponentTree(this.zaza);
                //this.zaza.addEventListener('click');
                // au lancement
                this.runWhenDomReady(() => {
                        this.zaza.componentRegistry.buildComponentTree(this.zaza);
                });
                this.zaza.show();
        }
        constructor() {
                super();
                this.zaza = new Zaza('zaza');
        }
} // class MyApplication
const myApplication = new MyApplication();
myApplication.run();
//# sourceMappingURL=zaza.js.map
